=== lonevvolf/kaichronicles/www/data/objects.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="effectClass">
        <xs:restriction base="xs:string">
            <xs:enumeration value="endurance">
                <xs:annotation>
                    <xs:documentation>The endurance will be increased</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="combatSkill">
                <xs:annotation>
                    <xs:documentation>The combat skill will be increased</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="backpackSlots">
                <xs:annotation>
                    <xs:documentation>The number of backpack slots will be increased (only for effect).</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="special">
                <xs:annotation>
                    <xs:documentation>Objects with complex behavior (only for usage). They are implemented on SpecialObjectsUse class, at specialObjectsUse.ts</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="object-mechanics">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="weapons">
                    <xs:annotation>
                        <xs:documentation>The list of weapons items.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="weapon" type="weapon" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="specials">
                    <xs:annotation>
                        <xs:documentation>The list of special items.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="special" type="special" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="objects">
                    <xs:annotation>
                        <xs:documentation>The list of normal items.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="object" type="object" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="weapon">
        <xs:complexContent>
            <xs:extension base="itemCommon">
                <xs:attribute name="weaponType" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>Optional. If it's set, the object can be used as a weapon of the given types.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="grdWpnmstryBonus" type="xs:boolean" default="true">
                    <xs:annotation>
                        <xs:documentation>Optional (true by default). If it's set, allows (or not) the weapon to inflict an additional 1 ENDURANCE point loss upon an enemy in every successful round of combat, if player have the rank of Sun Lord and have Grand Weaponmastery for this type of weapon (from book 16).</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="special">
        <xs:complexContent>
            <xs:extension base="object">
                <xs:attribute name="weaponType" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>Optional. If it's set, the object can be used as a weapon. In the property value is set the class of weapon as it can be used. If it can be more than one, each class is separated with a "|" character.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="grdWpnmstryBonus" type="xs:boolean" default="true">
                    <xs:annotation>
                        <xs:documentation>Optional (true by default). If it's set, allows (or not) the weapon to inflict an additional 1 ENDURANCE point loss upon an enemy in every successful round of combat, if player have the rank of Sun Lord and have Grand Weaponmastery for this type of weapon (from book 16).</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="isArrow" type="xs:boolean">
                    <xs:annotation>
                        <xs:documentation>Optional. If true, the object it's an Arrow, and it occupies an slot on a Quiver as a normal Arrow</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="object">
        <xs:complexContent>
            <xs:extension base="itemCommon">
                <xs:sequence>
                    <xs:element name="usage" type="usage" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
                <xs:attribute name="isMeal" type="xs:boolean" default="false">
                    <xs:annotation>
                        <xs:documentation>Optional. If true, the object can be eaten as a Meal.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="itemCount" type="xs:decimal" default="1">
                    <xs:annotation>
                        <xs:documentation>Optional. If set, specify how many "slots" the item takes in your backpack.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="usageCount" type="xs:integer" default="1">
                    <xs:annotation>
                        <xs:documentation>Optional. If set, specify how many times this item can be used.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="itemCommon">
        <xs:sequence>
            <xs:element name="name" minOccurs="1" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        The object name.
                    </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string"></xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="description" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        Optional. A extended description for the object.
                    </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string"></xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="extraDescription" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        Optional. A more extended description for the object.
                    </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string"></xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="image" type="image" minOccurs="0" maxOccurs="1" />
            <xs:element name="effect" type="effect" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>The special item id.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="droppable" type="xs:boolean">
            <xs:annotation>
                <xs:documentation>Optional. If it's false, the player will cannot drop the object</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="incompatibleWith" type="xs:string">
            <xs:annotation>
                <xs:documentation>Optional. If it's set, the player cannot pick the object if it already has some of the incompatible objects</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="image">
        <xs:annotation>
            <xs:documentation>Optional. It references to some book image for the object. The image should be at /www/data/projectAon/[BOOKNUMBER]/ill_en/[IMAGENAME].</xs:documentation>
        </xs:annotation>
        <xs:attribute name="book" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>Book number. If object image was drawed by different illustrators (Chalk / Williams), different books versions should be separated by a "|" character</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>The image file name.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="effect">
        <xs:annotation>
            <xs:documentation>Optional. If it's set, the object as some effect when it's carried.</xs:documentation>
        </xs:annotation>
        <xs:attribute name="class" type="effectClass" use="required">
            <xs:annotation>
                <xs:documentation>It says what is the effect of the object.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="increment" type="xs:integer" use="required">
            <xs:annotation>
                <xs:documentation>Add/remove points to the given class.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="usage">
        <xs:annotation>
            <xs:documentation>If it's set, the player can "use" the object, and then it will be dropped from the inventory if necessary.</xs:documentation>
        </xs:annotation>
        <xs:attribute name="class" type="effectClass" use="required">
            <xs:annotation>
                <xs:documentation>It says what is the effect of the object.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="increment" type="xs:integer">
            <xs:annotation>
                <xs:documentation>Add/remove points to the given class.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="priorCombat" type="xs:boolean" default="false">
            <xs:annotation>
                <xs:documentation>Optional. Endurance only. If true, allow use of the object prior a combat.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="takenWithMeal" type="xs:boolean" default="false">
            <xs:annotation>
                <xs:documentation>Optional. If true, it can only be used if the player has a meal or Grand Huntmastery (meal will be consumed)</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="takenWithLaumspur" type="xs:boolean" default="false">
            <xs:annotation>
                <xs:documentation>Optional. If true, it can only be used if the player has a Laumspur potion or Herbmastery (potion will be consumed)</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== lonevvolf/kaichronicles/www/data/objects.xml
<?xml version="1.0" encoding="utf-8"?>

<object-mechanics  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/cracrayol/kaichronicles/master/www/data/objects.xsd">

    <weapons>
        <!-- WEAPONS ON KAI / MAGNAKAI SERIES BOOKS -->
        <weapon id="axe">
            <name>Axe</name>
            <image book="1|9" name="axe.png" />
        </weapon>

        <weapon id="dagger">
            <name>Dagger</name>
            <image book="1|9" name="dagger.png" />
        </weapon>

        <weapon id="sword">
            <name>Sword</name>
            <image book="1|9" name="sword.png" />
        </weapon>

        <weapon id="spear">
            <name>Spear</name>
            <image book="1|9" name="spear.png" />
        </weapon>

        <weapon id="mace">
            <name>Mace</name>
            <image book="1|9" name="mace.png" />
        </weapon>

        <weapon id="shortsword">
            <name>Short Sword</name>
            <image book="1|9" name="ssword.png" />
        </weapon>

        <weapon id="quarterstaff" grdWpnmstryBonus="false">
            <name>Quarterstaff</name>
            <image book="1|9" name="qstaff.png" />
        </weapon>

        <weapon id="warhammer">
            <name>Warhammer</name>
            <image book="1|9" name="warhammr.png" />
        </weapon>

        <weapon id="broadsword">
            <name>Broad Sword</name>
            <image book="1|9" name="bsword.png" />
        </weapon>

        <!-- BOOK 3 -->

        <weapon id="bonesword" weaponType="sword">
            <name>Bone Sword</name>
            <image book="3" name="sword.png" />
        </weapon>

        <weapon id="bonedagger" weaponType="dagger">
            <name>Bone Dagger</name>
            <image book="3" name="small17.png" />
        </weapon>

        <!-- BOOK 4 -->

        <weapon id="captaindvalsword" weaponType="sword">
            <name>Captain D’Val’s Sword</name>
            <description>
                It has an inscription on the blade: ‘Captain Remir D’Val—King’s Guard Regiment’
            </description>
            <image book="1" name="sword.png" />
        </weapon>

        <!-- BOOK 5 -->

        <weapon id="jakan" weaponType="bow" grdWpnmstryBonus="false">
            <name>Jakan</name>
            <description>
                A hunting bow used by the coastal fishermen of Vassagonia
            </description>
            <image book="6" name="bow.png" />
        </weapon>

        <!-- BOOK 6 -->

        <weapon id="bow" grdWpnmstryBonus="false">
            <name>Bow</name>
            <image book="6|9" name="bow.png" />
        </weapon>

        <weapon id="broninwarhammer" weaponType="warhammer">
            <name>Bronin Warhammer</name>
            <description>
                Wrought of a metal called bronin. When you use it in combat it will add 1 point to your COMBAT SKILL
            </description>
            <image book="1" name="warhammr.png" />
            <effect class="combatSkill" increment="1" />
        </weapon>

        <!-- BOOK 18 -->
        <weapon id="luthadagger" weaponType="dagger">
            <name>Prince Lutha's Dagger</name>
            <image book="1|9" name="dagger.png" />
        </weapon>

        <!-- BOOK 25 -->
        <weapon id="halberd">
            <name>Halberd (Spear)</name>
            <image book="1|9" name="spear.png" />
        </weapon>

    </weapons>

    <specials>
        <!-- SPECIAL OBJECTS -->

        <!-- BOOK 1 -->

        <special id="helmet" incompatibleWith="silverhelm">
            <name>Helmet</name>
            <description>This adds 2 ENDURANCE points to your total.</description>
            <image book="1" name="helmet.png" />
            <effect class="endurance" increment="2" />
        </special>

        <special id="chainmail" incompatibleWith="chainmail|broninvest">
            <name>Chainmail Waistcoat</name>
            <description>This adds 4 ENDURANCE points to your total.</description>
            <image book="1" name="mail.png" />
            <effect class="endurance" increment="4" />
        </special>

        <special id="map" itemCount="0">
            <name>Map</name>
        </special>

        <special id="tombguardiangems">
            <name>20 Tomb Guardian Gems</name>
        </special>

        <special id="crystalstar">
            <name>Crystal Star Pendant</name>
            <description>
                It is the symbol of the Brotherhood of the Crystal Star 
                (the Magicians’ Guild of Toran)
            </description>
        </special>

        <!-- BOOK 2 -->

        <special id="shield" incompatibleWith="shield">
            <name>Shield</name>
            <description>This adds 2 points to your COMBAT SKILL</description>
            <image book="2" name="shield.png" />
            <effect class="combatSkill" increment="2" />
        </special>

        <special id="portbaxticket">
            <name>Ticket to Port Bax</name>
        </special>

        <special id="sommerswerd" weaponType="sword|broadsword|shortsword" grdWpnmstryBonus="false">
            <name>Sommerswerd</name>
            <description>
                When used in combat, the Sommerswerd will add 8 points to your COMBAT SKILL 
                (+ Weaponskill with swords).
            </description>
            <extraDescription>
                It has the ability to absorb any magic that is used against its bearer, and it doubles 
                the total of all ENDURANCE points lost by undead enemies in combat
            </extraDescription>
            <image book="2" name="ill5.png" />
            <effect class="combatSkill" increment="8" />
        </special>

        <special id="magicspear" weaponType="spear" grdWpnmstryBonus="false">
            <name>Magic Spear</name>
            <image book="1" name="spear.png" />
        </special>

        <special id="sealofhammerdal">
            <name>Seal of Hammerdal</name>
            <description>
                A golden ring bearing the royal arms of Durenor
            </description>
            <image book="2" name="seal.png" />
        </special>

        <special id="portbaxpapers">
            <name>Papers</name>
            <description>
                An envelope containing a sheaf of official-looking papers
            </description>
        </special>

        <special id="whitepass">
            <name>White Pass</name>
        </special>

        <special id="redpass">
            <name>Red Pass</name>
        </special>

        <!-- BOOK 3 -->

        <special id="leatherwaistcoat" incompatibleWith="leatherwaistcoat">
            <name>Padded Leather Waistcoat</name>
            <description>
                This adds 2 ENDURANCE points to your total
            </description>
            <image book="3" name="plw.png" />
            <effect class="endurance" increment="2" />
        </special>

        <special id="baknaroil" droppable="false">
            <!-- On books this is not really an object, just an "annotation" on 
                the action chart... -->
            <name>Baknar Oil on your skin</name>
            <description>
                Baknar oil gives excellent insulation from the bitter cold of Kalte
            </description>
        </special>

        <special id="diamond">
            <name>Diamond</name>
        </special>

        <special id="trianglebluestone">
            <name>Triangle of Blue Stone</name>
            <description>
                It is a small triangle of blue stone on a neck chain
            </description>
            <image book="3" name="small25.png" />
        </special>

        <special id="bracelet" droppable="false">
            <name>Bracelet</name>
            <description>
                A plain bracelet, without mark or inscription, and appear to be made of solid gold
            </description>
        </special>

        <special id="silverkeybook3">
            <name>Silver Key (Book 3)</name>
            <image book="1" name="small15.png" />
        </special>

        <special id="glowingcrystal">
            <name>Glowing Crystal</name>
            <image book="3" name="ill19.png" />
        </special>

        <special id="stoneeffigy">
            <name>Stone Effigy</name>
            <description>
                A small statuette of a strange tentacled creature
            </description>
            <image book="3" name="small10.png" />
        </special>

        <special id="bluestonedisc">
            <name>Blue Stone Disc</name>
        </special>

        <special id="firesphere">
            <name>Firesphere</name>
            <image book="3" name="small7.png" />
        </special>

        <special id="silverhelm" incompatibleWith="helmet">
            <name>Silver Helm</name>
            <description>
                If worn during combat, it will increase your COMBAT SKILL by 2 points
            </description>
            <image book="3" name="small26.png" />
            <effect class="combatSkill" increment="2" />
        </special>

        <special id="kalkothbonesword" weaponType="sword">
            <name>Kalkoth Rib Blade</name>
            <description>
                Adds 1 to your COMBAT SKILL when used in Kalte.
            </description>
            <image book="3" name="sword.png" />
        </special>

        <!-- BOOK 4 -->

        <special id="onyxmedallion">
            <name>Onyx Medallion</name>
            <image book="4" name="small3.png" />
        </special>

        <special id="scrollpoetry">
            <name>Scroll</name>
            <description>
                Upon the scroll is written the following verse:
            </description>
            <extraDescription>
                When the full moon shines o’er the temple deep, /
                A sacrifice will stir from sleep /
                The legions of a long forgotten lord. /
